image: franzos/ruby-node-gulp-java

cache:
  paths:
    - vendor/

before_script:
  - bundle install --path vendor

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn
    - gulp
    - JEKYLL_ENV=production bundle exec jekyll build -d public/
  artifacts:
    when: on_success
    paths:
      - public
    expire_in: 1h
    only:
      - master

deploy:
  stage: deploy
  script:
    - export S3_ID="$(echo "$S3_ID")"
    - export S3_SECRET="$(echo "$S3_SECRET")"
    - export S3_BUCKET="$(echo "$S3_BUCKET")"
    - export CLOUDFRONT_DISTRIBUTION_ID="$(echo "$CLOUDFRONT_DISTRIBUTION_ID")"
    - bundle exec s3_website push
  only:
    - master