image: 53hati/ruby-java

cache:
  paths: 
    - vendor/

before_script:
  - gem install bundler
  - bundle install --path vendor

build:
  stage: build
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d public/
  artifacts:
    paths:
      - public
  only:
    - master

vars:
  type: test
  script:
    - 'export S3_ID="$(echo "$S3_ID")" >> s3_deploy_vars'
    - 'export S3_SECRET="$(echo "$S3_SECRET")" > s3_deploy_vars'
    - 'export S3_BUCKET="$(echo "$S3_BUCKET")" > s3_deploy_vars'
    - 'export CLOUDFRONT_DISTRIBUTION_ID="$(echo "$CLOUDFRONT_DISTRIBUTION_ID")" > s3_deploy_vars'
  artifacts:
    paths:
      - s3_deploy_vars
  only:
    - master

deploy:
  stage: deploy
  script:
    - source s3_deploy_vars
    - bundle exec s3_website push
  artifacts:
    paths:
      - public
  only:
    - master