# Site
baseurl: "/resume" # for GitHub Pages
url: "https://franckclement.github.io" # for GitHub Pages

languages: ["fr", "en"]
exclude_from_localizations: ["javascript", "images", "css"]

lang-paths:
  - fr:
      base-url: "/"
  - en:
      base-url: "/en/"

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-multiple-languages-plugin